version: '3'

services:
  mysql:
    #image: sameersbn/mysql:5.7.22-1
    build:
      context: ./mysql
      args:
      - HTTP_PROXY=${HTTP_PROXY:-}
      - http_proxy=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - https_proxy=${HTTPS_PROXY:-}
      - NO_PROXY=${NO_PROXY:-}
      - no_proxy=${NO_PROXY:-}
    restart: always
    environment:
    #- TZ=Asia/Tokyo
    - DB_USER=redmine
    - DB_PASS=${DB_PASS}
    - DB_NAME=redmine_production
    volumes:
    #- /srv/docker/redmine/mysql:/var/lib/mysql
    - ./volumes/mysql:/var/lib/mysql
    #- ./volumes/mysql_logs:/var/log/mysql

  redmine:
    #image: sameersbn/redmine:4.1.1-9
    build:
      context: ./redmine
      args:
      - HTTP_PROXY=${HTTP_PROXY:-}
      - http_proxy=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - https_proxy=${HTTPS_PROXY:-}
      - NO_PROXY=${NO_PROXY:-}
      - no_proxy=${NO_PROXY:-}
    restart: always
    depends_on:
    - mysql
    environment:
    - TZ=Asia/Tokyo

    - DB_ADAPTER=mysql2
    - DB_HOST=mysql
    - DB_PORT=3306
    - DB_USER=redmine
    - DB_PASS=${DB_PASS}
    - DB_NAME=redmine_production

    - REDMINE_PORT=${REDMINE_PORT:-80}
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=false
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    - SESSION_KEY_SUFFIX=${SESSION_KEY_SUFFIX:-}

    ports:
    - "${REDMINE_PORT:-80}:80"
    volumes:
    #- /srv/docker/redmine/redmine_mysql:/home/redmine/data
    #- /srv/docker/redmine/redmine-logs:/var/log/redmine
    - ./volumes/redmine_data:/home/redmine/data
    - ./volumes/redmine_logs:/var/log/redmine

#volumes:
#  mysql
#    driver: local
#  redmine_data:
#    driver: local
#  redmine_logs:
#    driver: local
