production:
  deny_delete: false
  auto_create: true
  #force_repository: false
  #pre_create: /usr/local/bin/pre-create.sh
  post_create: /home/scm/scripts/post-create.sh
  #pre_delete: /usr/local/bin/pre-delete.sh
  #post_delete: /usr/local/bin/post-delete.sh
  #max_repos: 0
  #only_creator: false
  allow_add_local: true
  #allow_pickup: false
  svn:
    path:     /home/scm/repos/svn
    svnadmin: /usr/bin/svnadmin
    url: svn
  git:
    path: /home/scm/repos/git
    git:  /usr/bin/git
    options: --bare
    url: git
    #update_server_info: true
    #git_ext: true
    #append: trunk
#  mercurial:
#    path: /var/lib/mercurial
#    hg: /usr/bin/hg
#  bazaar:
#    path: /var/lib/bazaar
#    bzr: /usr/bin/bzr
#    init: init-repository
#    log_encoding: UTF-8
#  github:
#    path: /var/lib/github
#    api:
#      token: 36857b12efbccc64ce725ea8674fab6ecbd05c03
#      register_hook: true

development:
